// Azure Managed Grafana

param grafanaName string
param location string

resource grafana 'Microsoft.Dashboard/grafana@2023-09-01' = {
  name: grafanaName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  sku: {
    name: 'Standard'
  }
  properties: {
    apiKey: 'Disabled'
    deterministicOutboundIP: 'Disabled'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    grafanaIntegrations: {
      azureMonitorWorkspaceIntegrations: []
    }
  }
}

output grafanaId string = grafana.id
output grafanaName string = grafana.name
output grafanaEndpoint string = grafana.properties.endpoint
output grafanaPrincipalId string = grafana.identity.principalId
