// Runtime configuration — generated by CI/CD at deploy time.
// Do not edit this file manually; changes will be overwritten on next deploy.
//
// For local development, override these values before loading app.js:
//   window.COMPLIANCE_API_BASE = "https://<func-app>.azurewebsites.net/api/advisor";
//   window.COMPLIANCE_API_KEY  = "<function-key>";  // only needed outside SWA auth
